"""On-disk account-directory upgradeability.

Production persists account dirs across process restarts *and* across
deltachat-rpc-server upgrades and across the prober's own layout changes.
These tests guard that a dir written by an older setup still works with the
current code -- deterministically and without touching a relay.

L1: the prober's own per-relay -> flat layout migration (migrate_accounts.py)
    and the RelayPool startup guard that refuses the old layout.  Pure file /
    TOML shuffling (migrate_pool never opens dc.db), so it runs in tmp_path.

L2: a real accounts dir generated by an older release (2.49.0), opened by
    whatever deltachat-rpc-server is currently installed (floor is now >=2.53).
    This is a standing tripwire for core dc.db / accounts.toml format drift as
    the dependency floats up.  Network-free: real server, no relay.
"""

from __future__ import annotations

import shutil
from pathlib import Path

import pytest

from chatmail_prober.pool import RelayPool
from scripts.migrate_accounts import migrate_pool

# ---------------------------------------------------------------------------
# L1: the prober's own layout migration + startup guard
# ---------------------------------------------------------------------------


def _write_old_toml(path: Path, entries: list[tuple[str, str]]) -> None:
    """Write a per-relay accounts.toml (old layout) with (dir, uuid) entries."""
    ids = list(range(1, len(entries) + 1))
    lines = [
        "selected_account = 1",
        f"next_id = {len(entries) + 1}",
        f"accounts_order = [{', '.join(map(str, ids))}]",
        "",
    ]
    for i, (d, u) in zip(ids, entries):
        lines += ["[[accounts]]", f"id = {i}", f'dir = "{d}"', f'uuid = "{u}"', ""]
    path.write_text("\n".join(lines))


def _build_old_pool(pool_dir: Path, layout: dict[str, list[tuple[str, str]]]) -> None:
    """Create an old per-relay pool tree: worker-N/<relay>/accounts.toml + uuid dirs."""
    for relay, entries in layout.items():
        relay_dir = pool_dir / relay
        relay_dir.mkdir(parents=True)
        _write_old_toml(relay_dir / "accounts.toml", entries)
        for d, _uuid in entries:
            (relay_dir / d).mkdir()
            (relay_dir / d / "dc.db").write_bytes(b"")  # migrate never reads it


class TestLayoutMigration:
    def test_migrate_merges_relay_dirs_into_flat_layout(self, tmp_path):
        pool = tmp_path / "worker-0"
        _build_old_pool(pool, {
            "relay.a.example": [("uuidA1", "uuidA1"), ("uuidA2", "uuidA2")],
            "relay.b.example": [("uuidB1", "uuidB1")],
        })

        moved, errors = migrate_pool(pool, apply=True)
        assert (moved, errors) == (3, 0)

        # A single flat accounts.toml, renumbered 1..3.
        flat = pool / "accounts.toml"
        assert flat.exists()
        text = flat.read_text()
        assert text.count("[[accounts]]") == 3
        assert "next_id = 4" in text
        assert "accounts_order = [1, 2, 3]" in text
        for uuid in ("uuidA1", "uuidA2", "uuidB1"):
            assert f'dir = "{uuid}"' in text
            assert (pool / uuid / "dc.db").exists()  # data dir moved up

        # Old relay subdirs are gone.
        assert not (pool / "relay.a.example").exists()
        assert not (pool / "relay.b.example").exists()

    def test_dry_run_reports_without_moving(self, tmp_path):
        pool = tmp_path / "worker-0"
        _build_old_pool(pool, {"relay.a.example": [("uuidA1", "uuidA1")]})

        moved, errors = migrate_pool(pool, apply=False)
        assert errors == 0
        # Nothing moved; the old tree is untouched.
        assert (pool / "relay.a.example" / "accounts.toml").exists()
        assert not (pool / "accounts.toml").exists()

    def test_startup_guard_rejects_old_then_accepts_migrated(self, tmp_path, monkeypatch):
        """RelayPool must refuse the old layout, and accept it once migrated --
        the exact restart-after-upgrade path a prod operator hits."""
        pool = tmp_path / "worker-0"
        _build_old_pool(pool, {"relay.a.example": [("uuidA1", "uuidA1")]})

        # Old layout: guard raises before any server is spawned.
        with pytest.raises(SystemExit, match="Old per-relay"):
            RelayPool(pool)._start_rpc()

        migrate_pool(pool, apply=True)

        # Migrated layout: guard passes.  Stub Rpc so no real server spawns.
        monkeypatch.setattr("chatmail_prober.pool.Rpc", lambda *a, **k: _StubRpc())
        p = RelayPool(pool)
        p._start_rpc()  # must not raise
        assert p.maker is not None


class _StubRpc:
    def start(self) -> None:
        pass

    def close(self) -> None:
        pass


# ---------------------------------------------------------------------------
# L2: an old-version accounts dir must open on the current server
# ---------------------------------------------------------------------------

_FIXTURE = Path(__file__).parent / "fixtures" / "accounts_v2_49"


class TestOldVersionDirOpens:
    def test_v249_dir_opens_and_enumerates_on_current_core(self, tmp_path):
        """Copy the committed 2.49.0 accounts dir, open it with the installed
        (>=2.53) server, and confirm the account still enumerates and its config
        reads.  Catches dc.db / accounts.toml format drift on dependency bumps."""
        dc_rpc = pytest.importorskip("deltachat_rpc_client")

        work = tmp_path / "accounts"
        shutil.copytree(_FIXTURE, work)

        try:
            rpc = dc_rpc.Rpc(accounts_dir=str(work))
            rpc.start()
        except Exception as e:  # noqa: BLE001 - env issue, not a format break
            pytest.skip(f"deltachat-rpc-server unavailable: {e}")
        try:
            dc = dc_rpc.DeltaChat(rpc)
            accounts = dc.get_all_accounts()
            assert len(accounts) == 1, "the 2.49 fixture holds exactly one account"
            # Config written at fixture-creation time survives the version gap.
            assert accounts[0].get_config("addr") == "probe@fixture.example"
        finally:
            rpc.close()

    def test_account_maker_scan_finds_fixture_account(self, tmp_path):
        """The prober's reuse path (AccountMaker._scan_db_for_domain) must find
        the account in an old-version dir, not just raw enumeration."""
        dc_rpc = pytest.importorskip("deltachat_rpc_client")
        from chatmail_prober.accounts import AccountMaker

        work = tmp_path / "accounts"
        shutil.copytree(_FIXTURE, work)

        try:
            rpc = dc_rpc.Rpc(accounts_dir=str(work))
            rpc.start()
        except Exception as e:  # noqa: BLE001
            pytest.skip(f"deltachat-rpc-server unavailable: {e}")
        try:
            maker = AccountMaker(dc_rpc.DeltaChat(rpc))
            scan = maker._scan_db_for_domain("fixture.example", ())
            assert scan.total == 1, "scan must see the fixture account by domain"
        finally:
            rpc.close()
